### ISSUE TITLE
Android Keyboard (AOSP) has stopped

### ISSUE THREAD

**Issue by 10MINT** [thunkable/thunkable-issues#30]
### Platform
✕ Android companion

### Issue/Request Origin
Own experience

### Steps to Reproduce
1. Put text input anywhere
2. Click into the text box

### Expected Behavior
The keyboard should open from below

### Actual Behavior
Every time I click into the text input, a message appears, saying "Android Keyboard (AOSP) has stopped". I can click "OK", but I'm not able to make any keyboard inputs.
```
E/AndroidRuntime( 5455): FATAL EXCEPTION: main
E/AndroidRuntime( 5455): Process: com.android.inputmethod.latin, PID: 5455
E/AndroidRuntime( 5455): android.view.InflateException: Binary XML file line #30: Error inflating class com.android.inputmethod.latin.suggestions.SuggestionStripView
E/AndroidRuntime( 5455):        at android.view.LayoutInflater.createView(LayoutInflater.java:633)
E/AndroidRuntime( 5455):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
E/AndroidRuntime( 5455):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
E/AndroidRuntime( 5455):        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916)
E/AndroidRuntime( 5455):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
E/AndroidRuntime( 5455):        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
E/AndroidRuntime( 5455):        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
E/AndroidRuntime( 5455):        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
E/AndroidRuntime( 5455):        at com.android.inputmethod.keyboard.KeyboardSwitcher.onCreateInputView(KeyboardSwitcher.java:351)
E/AndroidRuntime( 5455):        at com.android.inputmethod.latin.LatinIME.onCreateInputView(LatinIME.java:727)
E/AndroidRuntime( 5455):        at android.inputmethodservice.InputMethodService.updateInputViewShown(InputMethodService.java:1108)
E/AndroidRuntime( 5455):        at android.inputmethodservice.InputMethodService.showWindowInner(InputMethodService.java:1493)
E/AndroidRuntime( 5455):        at android.inputmethodservice.InputMethodService.showWindow(InputMethodService.java:1468)
E/AndroidRuntime( 5455):        at android.inputmethodservice.InputMethodService$InputMethodImpl.showSoftInput(InputMethodService.java:433)
E/AndroidRuntime( 5455):        at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:203)
E/AndroidRuntime( 5455):        at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
E/AndroidRuntime( 5455):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 5455):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 5455):        at android.app.ActivityThread.main(ActivityThread.java:5343)
E/AndroidRuntime( 5455):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5455):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 5455):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
E/AndroidRuntime( 5455):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
E/AndroidRuntime( 5455): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 5455):        at java.lang.reflect.Constructor.newInstance(Native Method)
E/AndroidRuntime( 5455):        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
E/AndroidRuntime( 5455):        at android.view.LayoutInflater.createView(LayoutInflater.java:607)
E/AndroidRuntime( 5455):        ... 22 more
E/AndroidRuntime( 5455): Caused by: android.view.InflateException: Binary XML file line #45: Error inflating class android.widget.TextView
E/AndroidRuntime( 5455):        at android.view.LayoutInflater.createView(LayoutInflater.java:633)
E/AndroidRuntime( 5455):        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
E/AndroidRuntime( 5455):        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
E/AndroidRuntime( 5455):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
E/AndroidRuntime( 5455):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
E/AndroidRuntime( 5455):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
E/AndroidRuntime( 5455):        at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
E/AndroidRuntime( 5455):        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
E/AndroidRuntime( 5455):        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
E/AndroidRuntime( 5455):        at com.android.inputmethod.latin.suggestions.SuggestionStripView.<init>(SuggestionStripView.java:153)
E/AndroidRuntime( 5455):        at com.android.inputmethod.latin.suggestions.SuggestionStripView.<init>(SuggestionStripView.java:145)
E/AndroidRuntime( 5455):        ... 25 more
E/AndroidRuntime( 5455): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 5455):        at java.lang.reflect.Constructor.newInstance(Native Method)
E/AndroidRuntime( 5455):        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
E/AndroidRuntime( 5455):        at android.view.LayoutInflater.createView(LayoutInflater.java:607)
E/AndroidRuntime( 5455):        ... 35 more
E/AndroidRuntime( 5455): Caused by: android.content.res.Resources$NotFoundException: File res/drawable/btn_suggestion_lxx_light.xml from drawable resource ID #0x7f020038
E/AndroidRuntime( 5455):        at android.content.res.Resources.loadDrawableForCookie(Resources.java:2482)
E/AndroidRuntime( 5455):        at android.content.res.Resources.loadDrawable(Resources.java:2384)
E/AndroidRuntime( 5455):        at android.content.res.TypedArray.getDrawable(TypedArray.java:749)
E/AndroidRuntime( 5455):        at android.view.View.<init>(View.java:3742)
E/AndroidRuntime( 5455):        at android.widget.TextView.<init>(TextView.java:637)
E/AndroidRuntime( 5455):        at android.widget.TextView.<init>(TextView.java:632)
E/AndroidRuntime( 5455):        at android.widget.TextView.<init>(TextView.java:628)
E/AndroidRuntime( 5455):        ... 38 more
E/AndroidRuntime( 5455): Caused by: android.content.res.Resources$NotFound
W/BroadcastQueue(  948): Permission Denial: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to ProcessRecord{58387ac 5202:com.thunkable.live/u0a88} (pid=5202, uid=10088) requires android.permission.READ_LOGS due to sender android (uid 1000)
```

Tested on Moto E (1st gen) running Android 5.1

**Comment by 10MINT** [comment]
See the (german) screenshot
![screenshot_2018-07-11-14-07-19 1](https://user-images.githubusercontent.com/10596945/42570372-f971a65c-8513-11e8-82d1-6d43598c6559.png)

**Comment by mark-friedman** [comment]
Closing,  based on last comment.
